services:
  - type: web
    name: music-recommendations
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt && python -c "from sentence_transformers import SentenceTransformer; SentenceTransformer('sentence-transformers/all-MiniLM-L12-v1')"
    startCommand: gunicorn --bind 0.0.0.0:$PORT app:app --workers 1 --timeout 30 --max-requests 50 --max-requests-jitter 5 --preload --worker-tmp-dir /dev/shm
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.0"
      - key: DATABASE_URL
        fromDatabase:
          name: music-recommendations-db
          property: connectionString
      - key: FLASK_ENV
        value: production
      - key: FLASK_DEBUG
        value: "false"
      - key: SECRET_KEY
        generateValue: true
      - key: SENTENCE_TRANSFORMER_MODEL
        value: paraphrase-MiniLM-L3-v2
      - key: DEFAULT_RECOMMENDATION_LIMIT
        value: "5"
      - key: MAX_RECOMMENDATION_LIMIT
        value: "10"
      - key: LOG_LEVEL
        value: INFO

databases:
  - name: music-recommendations-db
    databaseName: music_recommendations
    user: music_user
    plan: free
    postgresMajorVersion: 15
