services:
  - type: web
    name: music-recommendations
    runtime: docker
    plan: free
    # Use pre-built Docker image instead of building from source
    image:
      url: docker.io/delkajuer/music-recommendations:latest
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: music-recommendations-db
          property: connectionString
      - key: FLASK_ENV
        value: production
      - key: FLASK_DEBUG
        value: "false"
      - key: SECRET_KEY
        generateValue: true
      - key: SENTENCE_TRANSFORMER_MODEL
        value: sentence-transformers/all-MiniLM-L12-v1
      - key: DEFAULT_RECOMMENDATION_LIMIT
        value: "5"
      - key: MAX_RECOMMENDATION_LIMIT
        value: "10"
      - key: LOG_LEVEL
        value: INFO
      - key: KAGGLE_USERNAME
        sync: false
      - key: KAGGLE_KEY
        sync: false

databases:
  - name: music-recommendations-db
    databaseName: music_recommendations
    user: music_user
    plan: free
    postgresMajorVersion: 15
